[package]
name = "http-status"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
htmd = "0.1.6"
http = "1.2.0"
scraper = "0.22.0"
tokio = { version = "1.42.0", features = ["full"] }
